- name: Install apache
  become: true
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present

- name: Clone tooling repo into /tmp
  become: true
  ansible.builtin.git:
    repo: https://github.com/Sheviantos1/tooling.git
    dest: /tmp/tooling
    force: yes

- name: Copy website content to /var/www/html
  become: true
  ansible.builtin.copy:
    src: /tmp/tooling/html/
    dest: /var/www/html/
    owner: apache
    group: apache
    mode: '0755'
    remote_src: yes

- name: Start httpd service
  become: true
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
